version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: quarkusaurus-postgres
    environment:
      POSTGRES_DB: quarkusaurus
      POSTGRES_USER: quarkus
      POSTGRES_PASSWORD: quarkus
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quarkus -d quarkusaurus"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: